### ISSUE TITLE
onClick Not working on Mesh

### ISSUE THREAD

**Issue by Carlos-AvilesBuitron** [artcom/react-three-arjs#22]
I am trying to fire an onClick function on a cube mesh that is a child of a Marker.
I get no errors but the function never fires on click.

Is this an issue or am I missing something?

Thanks

**Comment by j-era** [comment]
Fixed in `v0.5.2` (see b971d7f)
@Carlos-AvilesBuitron Thanks for the hint!

**Comment by Carlos-AvilesBuitron** [comment]
Thank you for the fast update. I'm not seeing it work though. I see what
you meant by adding the "pointer events none". But I still do not see the
event click happen on my mesh.
Can you add an onClick to the box mesh in your sample and have it just
window.alert? I'm trying to do exactly that but no alert shows.

Thanks again for your great work.

**Comment by j-era** [comment]
Okay, think it's generally working https://codesandbox.io/s/determined-smoke-eo3jbn?file=/src/index.js ..but I recognize that some clicks are not handled, maybe some frames missing the tracking. Could you try the example, maybe it's working good enough for your usecase?

**Comment by j-era** [comment]
I see there's still a problem on mobile devices. Works well on desktop in my case. Reopening..

**Comment by j-era** [comment]
There's a problem concerning portrait view. Ar.js generates a css margin-left which is taken into account in the r3f event system. I think the solution should be this [PR](https://github.com/artcom/react-three-arjs/pull/23/files)

**Comment by Carlos-AvilesBuitron** [comment]
I see, thanks for keeping up with this. Will you merge the PR today?

**Comment by LucusWebsites** [comment]
I am running into this problem as well, mesh click handlers are not fired.
Any updates on this?

**Comment by j-era** [comment]
Should be fixed in `0.5.6` Missed updating `projectionMatrixInverse` (https://github.com/artcom/react-three-arjs/blob/d821c16c975e17a18612a227e05caaf87b938239/src/ar/ar.jsx#L96)
Updated example -> https://codesandbox.io/s/jolly-hodgkin-ssu33
